baseurl      = "https://jasoncarpenter.me"
title        = "Jason Carpenter"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "DevOps Engineer"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Jason Carpenter"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [languages.en.params]
    subtitle  = "A simple theme for Hugo"

    [languages.en.params.logo]
      logoText = "hello world"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

  [[menu.main]]
    identifier = "cv"
    name       = "CV"
    url        = "/cv"

[[params.social]]
  name = "email"
  url = "mailto:jason@jasoncarpenter.me"

[[params.social]]
  name = "github"
  url = "https://github.com/boweevil"

[[params.social]]
  name = "gitlab"
  url = "https://gitlab.com/boweevil"

[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/jason-phillip-carpenter/"

[[params.social]]
  name = "youtube"
  url = "https://youtube.com/@linuxdork"
